services:
# DB-START
    db:
        container_name: go_db
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_EXTERNAL_PORT}:${DB_PORT}"
        volumes:
            - ./volumes/postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
            interval: 3s
            retries: 5
# DB-END

    go_backend:
        container_name: go_backend
# DB-START
        depends_on:
            db:
                condition: service_healthy
# DB-END
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - "${EXTERNAL_PORT}:${PORT}"
        env_file:
            - .env
        dns:
            - 8.8.8.8
