services:
    go_db:
        container_name: go_db
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_EXTERNAL_PORT}:${DB_PORT}"
        volumes:
            - ./volumes/postgres_data:/var/lib/postgresql/data

    go_backend:
        container_name: go_backend
        build:
            dockerfile: Dockerfile
        ports:
            - "${EXTERNAL_PORT}:${PORT}"
        env_file:
            - .env
