// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
	"github.com/carsonkrueger/main/internal/templates/datadisplay"
	"github.com/carsonkrueger/main/internal/templates/partials/productcard"
)

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-col lg:gap-16 lg:pt-16 pt-8 pb-6 gap-6 items-center\"><section id=\"hero\" class=\"flex flex-col items-center lg:gap-12 gap-6 text-secondary min-h-[60vh]\"><div id=\"tree\" class=\"bg-[url(/public/tree.svg)] bg-center bg-contain bg-no-repeat text-center lg:h-130 h-100 flex flex-col justify-center items-center text-white font-[naervik]\"><h1 class=\"lg:text-[3rem] text-[2rem] font-black\" style=\"text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.9);\">Unlock Your Potential Naturally</h1><h3 class=\"lg:text-[1.8rem] text-[1.1rem] font-black\" style=\"text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.9);\">Premium Peptides for Study</h3><h3 class=\"lg:text-[1.8rem] text-[1.1rem] font-black\" style=\"text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.9);\">Potent. Proven. Powerful.</h3></div><div id=\"attributes\" class=\"flex items-center justify-center lg:gap-12 gap-6 text-secondary\"><icon-group class=\"flex flex-col gap-2 justify-center items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = datadisplay.Icon(datadisplay.AntioxidantIcon, datadisplay.XL4, datadisplay.Secondary).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = datadisplay.CircleOutline(datadisplay.Secondary, datadisplay.XL11, nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>Antioxidant</p></icon-group> <icon-group class=\"flex flex-col gap-2 justify-center items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = datadisplay.Icon(datadisplay.LeafIcon, datadisplay.XL4, datadisplay.Secondary).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = datadisplay.CircleOutline(datadisplay.Secondary, datadisplay.XL11, nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<p>Anti Aging</p></icon-group> <icon-group class=\"flex flex-col gap-2 justify-center items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = datadisplay.Icon(datadisplay.FlexIcon, datadisplay.XL4, datadisplay.SecondaryLo).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = datadisplay.CircleOutline(datadisplay.SecondaryLo, datadisplay.XL11, nil).Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p>Vitality</p></icon-group></div></section><section id=\"products\" class=\"flex flex-col gap-4 w-full py-8 px-4 text-secondary\"><section-header class=\"text-xl text-center\">Featured Products</section-header><div class=\"flex items-center justify-center flex-wrap lg:gap-10 gap-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = productcard.ProductCard(productcard.Props{
			Title: "Vitality Boost",
			Desc:  "Supports Energy & Focus",
			Img: productcard.ImgProps{
				Src: "/public/peptide.webp",
				Alt: "Peptide",
			},
			BtnText: "Add to Cart",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = productcard.ProductCard(productcard.Props{
			Title: "Vitality Boost",
			Desc:  "Supports Energy & Focus",
			Img: productcard.ImgProps{
				Src: "/public/peptide.webp",
				Alt: "Peptide",
			},
			BtnText: "Add to Cart",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = productcard.ProductCard(productcard.Props{
			Title: "Vitality Boost",
			Desc:  "Supports Energy & Focus",
			Img: productcard.ImgProps{
				Src: "/public/peptide.webp",
				Alt: "Peptide",
			},
			BtnText: "Add to Cart",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
