//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package auth

import (
	"time"
)

type Roles struct {
	ID        int16 `sql:"primary_key"`
	Name      string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}
