// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package datainput

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/carsonkrueger/main/util/validate"
)

func PasswordAttrs(id string) templ.Attributes {
	return templ.Attributes{
		"id":          id,
		"type":        "password",
		"name":        "password",
		"required":    true,
		"pattern":     validate.PasswordValidator.Regex.String(),
		"hx-validate": true,
	}
}

func EmailAttrs(id string, required bool) templ.Attributes {
	return templ.Attributes{
		"id":          id,
		"type":        "text",
		"name":        "email",
		"required":    required,
		"hx-validate": true,
		"pattern":     validate.EmailValidator.Regex.String(),
	}
}

func NameAttrs(id string, required bool) templ.Attributes {
	return templ.Attributes{
		"id":          id,
		"type":        "text",
		"name":        id,
		"required":    required,
		"hx-validate": true,
		"pattern":     validate.NameValidator.Regex.String(),
	}
}

func Input(attrs templ.Attributes) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if attrs != nil {
			templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " class=\"app-input\" _=\"on blur add .touched on me\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
